import { randomUUID, createHash } from "node:crypto";

import {
    Annotation,
    END,
    START,
    StateGraph,
} from "@langchain/langgraph";
import {
    ChatPromptTemplate,
    MessagesPlaceholder,
} from "@langchain/core/prompts";
import { ChatOpenAI } from "@langchain/openai";
import {
    AIMessage,
    type BaseMessage,
    ToolMessage,
    type ToolCall,
} from "@langchain/core/messages";

import {
    tools,
    toolMap,
} from "./tools/index.ts";

const MAX_TOOL_STEPS = Number(process.env.AGENT_MAX_TOOL_STEPS) || 6;
const MAX_TOOL_CALLS = Number(process.env.AGENT_MAX_TOOL_CALLS) || 10;
const TOOL_TIMEOUT_MS = Number(process.env.AGENT_TOOL_TIMEOUT_MS) || 30_000;
const AGENT_TIMEOUT_MS = Number(process.env.AGENT_TIMEOUT_MS) || 60_000;
const RETRY_COUNT = Number(process.env.AGENT_RETRY_COUNT) || 1;

/* eslint-disable new-cap */
const AgentStateAnnotation = Annotation.Root({
    messages: Annotation<BaseMessage[]>({
        reducer: (prev, next) => [...prev, ...next],
        default: () => [],
    }),
    toolSteps: Annotation<number>({
        reducer: (prev, next) => prev + next,
        default: () => 0,
    }),
});

/* eslint-enable new-cap */
export type AgentState = typeof AgentStateAnnotation.State;

/**
 * Type guard that checks if a message was generated by the assistant.
 * @param {BaseMessage | undefined} message The message to check.
 * @return {boolean} True when the message is from the AI.
 */
function isAI(message?: BaseMessage): message is AIMessage {
    return Boolean(message) && message?.getType() === "ai";
}

/**
 * JSON stringify with sorted keys for consistent output.
 * @param {unknown} obj The object to stringify.
 * @return {string} A stable JSON string.
 */
function jsonStringifySorted(obj: unknown): string {
    if (obj === null || typeof obj !== "object") {
        return JSON.stringify(obj);
    }
    if (Array.isArray(obj)) {
        return `[${obj.map(jsonStringifySorted).join(",")}]`;
    }
    const pairs = Object.keys(obj)
        .sort()
        .map((k) => `${JSON.stringify(k)}:${jsonStringifySorted(
            (obj as Record<string, unknown>)[k],
        )}`);
    return `{${pairs.join(",")}}`;
}

/**
 * Generate a fingerprint for deduplication.
 * @param {ToolCall} call The tool call.
 * @return {string} A short hash.
 */
function fingerprint(call: ToolCall): string {
    const payload = `${call.name}:${jsonStringifySorted(call.args ?? {})}`;
    return createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

/**
 * Wrap a promise with timeout.
 * @param {Promise<T>} promise The promise.
 * @param {number} ms Timeout in ms.
 * @param {string} label Label for error.
 * @return {Promise<T>} Result or timeout error.
 */
function withTimeout<T>(promise: Promise<T>, ms: number, label: string) {
    return Promise.race([
        promise,
        new Promise<never>((_, reject) =>
            setTimeout(() => reject(new Error(`${label} timed out`)), ms),
        ),
    ]);
}

/**
 * Execute with AbortController timeout support.
 * @param {Function} fn Function receiving AbortSignal.
 * @param {number} ms Timeout in ms.
 * @param {string} label Label for error.
 * @return {Promise<T>} Result or timeout error.
 */
async function withAbortTimeout<T>(
    fn: (signal: AbortSignal) => Promise<T>,
    ms: number,
    label: string,
): Promise<T> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), ms);

    try {
        return await fn(controller.signal);
    } catch (error) {
        if (controller.signal.aborted) {
            throw new Error(`${label} timed out`);
        }
        throw error;
    } finally {
        clearTimeout(timeoutId);
    }
}

/**
 * Retry an async function on failure.
 * @param {Function} fn The function.
 * @param {number} retries Retry count.
 * @return {Promise<T>} Result.
 */
async function withRetry<T>(fn: () => Promise<T>, retries: number) {
    let lastError: Error | undefined;
    for (let i = 0; i <= retries; i++) {
        try {
            return await fn();
        } catch (e) {
            lastError = e instanceof Error ? e : new Error(String(e));
        }
    }
    throw lastError;
}

export type ReActAgentConfig = {
    model: string;
    apiKey: string;
    baseURL?: string;
    temperature?: number;
    systemPrompt: string;
};

/**
 * Decide whether the agent should continue with tool execution or stop.
 * @param {AgentState} state The current agent state.
 * @return {string} The next edge target.
 */
function shouldContinue(state: AgentState): string {
    const lastMessage = state.messages.at(-1);

    if (!isAI(lastMessage)) return END;
    if (!lastMessage.tool_calls?.length) return END;
    if (state.toolSteps >= MAX_TOOL_STEPS) return END;

    return "tools";
}

/**
 * Execute pending tool calls requested by the model.
 * @param {AgentState} state The current agent state.
 * @return {Promise} Tool execution results.
 */
async function callTools(
    state: AgentState,
): Promise<{ messages: ToolMessage[]; toolSteps: number }> {
    const lastMessage = state.messages.at(-1);
    const toolCalls = isAI(lastMessage) ? lastMessage.tool_calls ?? [] : [];

    if (!toolCalls.length) {
        return { messages: [], toolSteps: 0 };
    }

    const limitedCalls = toolCalls.slice(0, MAX_TOOL_CALLS);

    const seen = new Set<string>();
    const uniqueCalls = limitedCalls.filter((call) => {
        const fp = fingerprint(call);
        if (seen.has(fp)) return false;
        seen.add(fp);
        return true;
    });

    const results = await Promise.all(
        uniqueCalls.map(async (call) => {
            const toolId = call.id ?? randomUUID();
            const tool = toolMap[call.name];

            if (!tool) {
                return new ToolMessage({
                    tool_call_id: toolId,
                    content: `Tool ${call.name} is not implemented.`,
                    status: "error",
                });
            }

            try {
                const result = await withRetry(
                    () => withAbortTimeout(
                        (signal) => tool.invoke(call.args, { signal }),
                        TOOL_TIMEOUT_MS,
                        call.name,
                    ),
                    RETRY_COUNT,
                );
                const content = typeof result === "string" ?
                    result :
                    JSON.stringify(result);

                return new ToolMessage({ tool_call_id: toolId, content });
            } catch (error) {
                const msg = error instanceof Error ?
                    error.message :
                    "Unknown error";
                return new ToolMessage({
                    tool_call_id: toolId,
                    content: `Failed to run ${call.name}: ${msg}`,
                    status: "error",
                });
            }
        }),
    );

    return { messages: results, toolSteps: 1 };
}

/**
 * Compile a LangGraph-powered ReAct agent with Tavily search capabilities.
 * @param {ReActAgentConfig} config The agent configuration.
 * @return {CompiledStateGraph} The compiled graph ready for invocation.
 */
export function createReActAgent(config: ReActAgentConfig) {
    const prompt = ChatPromptTemplate.fromMessages([
        ["system", config.systemPrompt],
        new MessagesPlaceholder("messages"),
    ]);

    const llm = new ChatOpenAI({
        apiKey: config.apiKey,
        model: config.model,
        temperature: config.temperature ?? 0.4,
        configuration: config.baseURL ? { baseURL: config.baseURL } : undefined,
    }).bindTools(tools);

    const agentChain = prompt.pipe(llm);

    const workflow = new StateGraph(AgentStateAnnotation)
        .addNode("agent", async (state: AgentState) => {
            const response = await agentChain.invoke(state);
            return { messages: [response], toolSteps: 0 };
        })
        .addNode("tools", callTools)
        .addEdge(START, "agent")
        .addConditionalEdges("agent", shouldContinue, ["tools", END])
        .addEdge("tools", "agent");

    const compiled = workflow.compile();

    type InvokeParams = Parameters<typeof compiled.invoke>;
    const originalInvoke = compiled.invoke.bind(compiled);
    compiled.invoke = ((input: InvokeParams[0], cfg?: InvokeParams[1]) =>
        withTimeout(originalInvoke(input, cfg), AGENT_TIMEOUT_MS, "Agent")
    ) as typeof compiled.invoke;

    return compiled;
}
